#!/bin/bash
if [[ "$(uname)" == "Darwin" ]]; then
#Check to see if you have homebrew installed. If not, the following 2 lines installs it for you.
    if [[ "$(which brew)" == "" ]]; then
      xcode-select --install
      /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi
    # Install node/npm and react-native.
    brew install node
    npm install -g npm@4.6.1
    npm install -g react-native
    npm install -g create-react-native-app
#For Debian based distros
else
    sudo apt-get update && sudo apt upgrade
	sudo apt-get install nodejs npm
    npm install -g npm@4.6.1
    npm install -g react-native
    npm install -g create-react-native-app
fi	
echo "Installed Node.js, NPM, and React-Native"
